configfile: "config.yaml"

OUTDIR = "data"

rule all:
    input:
        expand(
            "data/{netname}_{iteration}.npz",
            netname=config["netnames"],
            iteration=[str(i) for i in config["iterations"]],
        )

rule gen_or_load_network:
    """
    Stage I / Step 1: Generate/load base network.
    """
    output:
        net="data/{netname}_{iteration}.npz"
    conda:
        "envs/gen.yml"
    shell:
        r"""
        python scripts/network_generation.py \
          --netname "{wildcards.netname}" \
          --iteration "{wildcards.iteration}" \
          --out "{output.net}"
        """
